function [RECORDING_SESSION_LABEL,identifier,IA_ID,IA_LABEL,IA_REGRESSION_PATH_DURATION,IA_FIRST_FIXATION_DURATION,IA_SECOND_FIXATION_DURATION,IA_SKIP,IA_DWELL_TIME,IA_FIRST_RUN_DWELL_TIME,IA_FIRST_RUN_FIXATION_COUNT,IA_FIRST_FIX_PROGRESSIVE,IA_LEFT,IA_RIGHT,indexia1,TRIAL_INDEX] = importfile1(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as column vectors.
%   [RECORDING_SESSION_LABEL,IDENTIFIER,IA_ID,IA_LABEL,IA_REGRESSION_PATH_DURATION,IA_FIRST_FIXATION_DURATION,IA_SECOND_FIXATION_DURATION,IA_SKIP,IA_DWELL_TIME,IA_FIRST_RUN_DWELL_TIME,IA_FIRST_RUN_FIXATION_COUNT,IA_FIRST_FIX_PROGRESSIVE,IA_LEFT,IA_RIGHT,INDEXIA1,TRIAL_INDEX]
%   = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [RECORDING_SESSION_LABEL,IDENTIFIER,IA_ID,IA_LABEL,IA_REGRESSION_PATH_DURATION,IA_FIRST_FIXATION_DURATION,IA_SECOND_FIXATION_DURATION,IA_SKIP,IA_DWELL_TIME,IA_FIRST_RUN_DWELL_TIME,IA_FIRST_RUN_FIXATION_COUNT,IA_FIRST_FIX_PROGRESSIVE,IA_LEFT,IA_RIGHT,INDEXIA1,TRIAL_INDEX]
%   = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [RECORDING_SESSION_LABEL,identifier,IA_ID,IA_LABEL,IA_REGRESSION_PATH_DURATION,IA_FIRST_FIXATION_DURATION,IA_SECOND_FIXATION_DURATION,IA_SKIP,IA_DWELL_TIME,IA_FIRST_RUN_DWELL_TIME,IA_FIRST_RUN_FIXATION_COUNT,IA_FIRST_FIX_PROGRESSIVE,IA_LEFT,IA_RIGHT,indexia1,TRIAL_INDEX]
%   = importfile1('JX_37_IA_expanded.txt',2, 3244);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/05/23 11:19:37

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[3,5,6,7,8,9,10,11,12,13,14,15,16]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [3,5,6,7,8,9,10,11,12,13,14,15,16]);
rawCellColumns = raw(:, [1,2,4]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
RECORDING_SESSION_LABEL = rawCellColumns(:, 1);
identifier = rawCellColumns(:, 2);
IA_ID = cell2mat(rawNumericColumns(:, 1));
IA_LABEL = rawCellColumns(:, 3);
IA_REGRESSION_PATH_DURATION = cell2mat(rawNumericColumns(:, 2));
IA_FIRST_FIXATION_DURATION = cell2mat(rawNumericColumns(:, 3));
IA_SECOND_FIXATION_DURATION = cell2mat(rawNumericColumns(:, 4));
IA_SKIP = cell2mat(rawNumericColumns(:, 5));
IA_DWELL_TIME = cell2mat(rawNumericColumns(:, 6));
IA_FIRST_RUN_DWELL_TIME = cell2mat(rawNumericColumns(:, 7));
IA_FIRST_RUN_FIXATION_COUNT = cell2mat(rawNumericColumns(:, 8));
IA_FIRST_FIX_PROGRESSIVE = cell2mat(rawNumericColumns(:, 9));
IA_LEFT = cell2mat(rawNumericColumns(:, 10));
IA_RIGHT = cell2mat(rawNumericColumns(:, 11));
indexia1 = cell2mat(rawNumericColumns(:, 12));
TRIAL_INDEX = cell2mat(rawNumericColumns(:, 13));


